
export * from './home/home'
export * from './inbox/inbox'
export * from './dialog/dialog'
export * from './class-wall/class-wall'
export * from './calender/calendar'
export * from './gallery/gallery'
export * from './take-photo/take-photo'
export * from './view-photo/view-photo'
export * from './teacher-parent/teacher-parent.page'
