
export * from './class-tab/class-tab'
export * from './class-details/class-details'
export * from './create-class/create-class'
export * from './create-school/create-school'
export * from './home/home'
export * from './me-tab/me-tab'
export * from './school-tab/school-tab'
export * from './school-details/school-details'
export * from './student-tab/student-tab'
export * from './teacher-tab/teacher-tab'
