
export * from './attendance/attendance'
export * from './calender/calendar'
export * from './class-wall/class-wall'
export * from './gallery/gallery'
export * from './home/home'
export * from './inbox/inbox'
export * from './teacher-chat/teacher-chat'
export * from './view-photo/view-photo'
export * from './albums/albums'
export * from './album/album'
export * from './weekly-activities/weekly-activities'
export * from './view-weekly-activity/view-weekly-activity'
export * from './weekly-meal-menu/weekly-meal-menu'
export * from './view-weekly-meal-menu/view-weekly-meal-menu'
export * from './dialog/dialog'
export * from './homework/homework'
